### ISSUE TITLE
[BUG] - Botão Drawer desabilitado (HOME)

### ISSUE THREAD

**Issue by carolinabarros1** [Is-It-Safe/mobile#241]
## Task

- [x] Replicar bug
- [x] Identificar possíveis motivos
- [x] Problema identificado
   - [x] Correção na Home page 
   - [x] Correção no Safe Profile header
   - [x] Correção no Profile header
   - [x] Correção na Account header 

## Description
Na tela Home, ao clicar para abrir Drawer, nada acontece

## Steps to Reproduce (if applicable)

Logar com uma conta existente;
Ir para tela "Home";
Clicar para abrir Drawer.

## Expected behavior
Abrir Drawer com funcionalidades como "Minha Conta" e outras.

## Actual behavior

Drawer desabilitado

## Screenshots or Logs

[If applicable, include screenshots or relevant logs to help explain the issue.]

## Environment

Operating System: Android 10
Browser (if applicable):
Version: 1.0.5+3

## Additional Information

[Add any other relevant information about the issue or feature request here.]

**Comment by NiltonFirmino** [comment]
## Documentação do problema

O bug acontecia quando o usuário realizava o cadastro sem escolher previamente seu profile photo, quando o mesmo realizava o login recebia essa json de response, com o profilePhoto vazio, "":

```json
{
   "id":5,
   "profilePhoto":"",
   "fullName":"Nilton",
   "nickname":"Firmino",
   "pronoun":"ele/dele",
   "gender":"Homem Cis",
   "orientation":"Heterossexual",
   "birthDate":"29/04/1987",
   "reviews":[]
}
```

Porem o nosso código não estava preparado para lidar com empty string no momento de exibição da profile photo, ajustes foram realizados nos pontos mencionados na task
